name: Publish Plugin

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089
        with:
          persist-credentials: false
      - uses: ./.github/actions/plugin-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CDN_HOST: ${{ secrets.CDN_HOST }}
          CDN_USER: ${{ secrets.CDN_USER }}
          CDN_PRIVATE_KEY: ${{ secrets.CDN_PRIVATE_KEY }}
          CDN_PRIVATE_KEY_PASS: ${{ secrets.CDN_PRIVATE_KEY_PASS }}
          CDN_ROOT_PATH: ${{ secrets.CDN_ROOT_PATH }}
